#!/bin/tcsh
# quickly updates only trigger.html

set default=500

if ( ! ($?BEAM) ) then
  echo "BEAM env variable not set!"
  setenv BEAM $default
  echo "Defaulting to BEAM=${BEAM}"
endif

root -b -q 'trgMon.C('${BEAM}')'
#./mkHTMLfile runs.html 1
#./mkHTMLfile shiftlong.html 2
#./mkHTMLfile shiftshort.html 3
./mkTriggerPage

mv -v *.html *.png goodruns.dat badruns.dat runlog.root $BEAM/
./copyToProtected
#cp -r $BEAM /afs/rhic/star/doc_protected/www/docp11/spin/dilks/trgmon/
